#!/usr/bin/env bash
#
# bootstrap-new-mac/post-install-mac.sh
#
# Install selected software and copy prepared configuration files.
#
# IMPORTANT:
#   Configuration content is NOT generated by this script.
#   Put the desired source files in ./config/ and this script copies them.
#
# Selector:
#   ↑/↓ Move
#   Space Select
#   A Select all
#   N Select none
#   Enter Continue
#   Q Quit
#
# Test:
#   ./post-install-mac.sh --test
#
# Test mode makes NO changes.
#

set -uo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/config"

AUTO=false
TEST_MODE=false

SCRIPT_START=$(date +%s)
HEARTBEAT_INTERVAL=120
HB_RUNNING=true
HB_PID=""

MAGENTA="\033[0;35m"
YELLOW="\033[0;33m"
ORANGE="\033[38;5;208m"
GREEN="\033[0;32m"
RED="\033[0;31m"
BOLD="\033[1m"
RESET="\033[0m"
CYAN="\033[0;36m"
PINK="\033[1;35m"

#INSTALLED=()
#SKIPPED=()
#CONFIGURED=()
#WARNINGS=()
#FAILED=()

# To this instead:
declare -a INSTALLED SKIPPED CONFIGURED WARNINGS FAILED

while [ "$#" -gt 0 ]; do
    case "$1" in
        --test)
            TEST_MODE=true
            shift
            ;;
        --yes|--auto)
            AUTO=true
            shift
            ;;
        -h|--help)
            cat <<'EOF'
Usage:
  ./post-install-mac.sh
  ./post-install-mac.sh --test
  ./post-install-mac.sh --yes

Normal mode:
  Opens the selector. Everything is selected by default.

--test:
  Opens the selector and simulates the selected plan.
  No installation or configuration changes are made.

--yes:
  Selects everything and runs without the selector.
EOF
            exit 0
            ;;
        *)
            printf "%b[ERROR]%b Unknown argument: %s\n" "$RED" "$RESET" "$1"
            exit 1
            ;;
    esac
done

format_duration() {
    local t="$1"
    local h=$((t / 3600))
    local m=$(((t % 3600) / 60))
    local s=$((t % 60))
    if [ "$h" -gt 0 ]; then
        printf "%02d:%02d:%02d" "$h" "$m" "$s"
    elif [ "$m" -gt 0 ]; then
        printf "%02d:%02d" "$m" "$s"
    else
        printf "%ds" "$s"
    fi
}

section() {
    printf "\n%b%b=================================================================%b\n" "$YELLOW" "$BOLD" "$RESET"
    printf "%b  %s%b\n" "$YELLOW" "$1" "$RESET"
    printf "%b=================================================================%b\n\n" "$YELLOW" "$RESET"
}

info()  { printf "%b[INFO]%b %s\n" "$MAGENTA" "$RESET" "$1"; }
ok()    { printf "%b[OK]%b %s\n" "$GREEN" "$RESET" "$1"; }
skip()  { printf "%b[SKIP]%b %s\n" "$YELLOW" "$RESET" "$1"; }
warn()  { printf "%b[WARN]%b %s\n" "$ORANGE" "$RESET" "$1"; }
error() { printf "%b[ERROR]%b %s\n" "$RED" "$RESET" "$1"; }

record() {
    local array_name="$1"
    local value="$2"
    eval "$array_name+=(\"\$value\")"
}

run_task() {
    local label="$1"
    shift
    info "$label"

    local start status elapsed
    start=$(date +%s)

    if "$@"; then status=0; else status=$?; fi

    elapsed=$(( $(date +%s) - start ))

    if [ "$status" -eq 0 ]; then
        ok "$label ($(format_duration "$elapsed"))"
        record INSTALLED "$label"
    else
        error "$label failed (exit $status)"
        record FAILED "$label"
    fi
    return 0
}

backup_target() {
    local target="$1"
    [ -e "$target" ] || return 0

    local backup="${target}.bak-$(date +%Y%m%d-%H%M%S)"
    if cp -p "$target" "$backup"; then
        ok "Backup created: $backup"
        return 0
    fi

    error "Could not back up: $target"
    record FAILED "Backup failed: $target"
    return 1
}

copy_config() {
    local source="$1"
    local target="$2"
    local label="$3"

    if [ ! -f "$source" ]; then
        error "$label source file not found: $source"
        record FAILED "$label: source file missing"
        return 0
    fi

    local target_dir
    target_dir="$(dirname "$target")"

    if [ -d "$target_dir" ]; then
        info "$label target directory already exists: $target_dir"
    else
        info "$label target directory does not exist; creating: $target_dir"
        if mkdir -p "$target_dir"; then
            ok "Created directory: $target_dir"
        else
            error "Could not create directory: $target_dir"
            record FAILED "$label: target directory creation failed"
            return 0
        fi
    fi

    if [ -e "$target" ]; then
        info "$label target already exists; backing it up."
        backup_target "$target" || return 0
    fi

    if cp -p "$source" "$target"; then
        ok "$label copied to $target"
        record CONFIGURED "$label"
    else
        error "Could not copy $source -> $target"
        record FAILED "$label: copy failed"
    fi
}

brew_formula_present() { brew list --formula "$1" >/dev/null 2>&1; }
brew_cask_present() { brew list --cask "$1" >/dev/null 2>&1; }

install_formula() {
    local formula="$1"
    local label="${2:-$1}"
    if brew_formula_present "$formula"; then
        skip "$label — already installed."
        record SKIPPED "$label"
    else
        run_task "Installing $label" brew install "$formula"
    fi
}

install_cask() {
    local cask="$1"
    local label="${2:-$1}"
    if brew_cask_present "$cask"; then
        skip "$label — already installed."
        record SKIPPED "$label"
    else
        run_task "Installing $label" brew install --cask "$cask"
    fi
}

ITEM_IDS=(
    homebrew
    coreutils
    htop
    btop
    starship
    ghostty
    jetbrains_mono_nerd_font
    caskaydia_mono_nerd_font
    nvm
    node20
    node22
    node_default22
    java17
    python3
    stats
    itsycal
    vlc
    brave_browser
    duckduckgo
    firefox
    telegram
    sublime_text
    transmission
    outline_manager
    localsend
    intellij_idea_ce
    raycast
    login_stats
    login_itsycal
    login_raycast
    bash_profile
    bashrc
    shell_tools
    starship_config
    ghostty_config
)

ITEM_LABELS=(
    "Homebrew"
    "coreutils"
    "htop"
    "btop"
    "Starship"
    "Ghostty"
    "JetBrains Mono Nerd Font"
    "CaskaydiaMono Nerd Font"
    "NVM"
    "Node.js 20"
    "Node.js 22"
    "Node.js default version: 22"
    "Java 17 (Azul Zulu JDK 17)"
    "Python 3"
    "Stats"
    "Itsycal"
    "VLC"
    "Brave Browser"
    "DuckDuckGo"
    "Firefox"
    "Telegram"
    "Sublime Text"
    "Transmission"
    "Outline Manager"
    "LocalSend"
    "IntelliJ IDEA Community Edition"
    "Raycast"
    "macOS Login Item: Stats"
    "macOS Login Item: Itsycal"
    "macOS Login Item: Raycast"
    "~/.bash_profile"
    "~/.bashrc"
    "~/.shell-tools"
    "~/.config/starship.toml"
    "Ghostty configuration"
)

SELECTED=()
for _ in "${ITEM_IDS[@]}"; do SELECTED+=(1); done

set_selected() {
    local id="$1" value="$2" i
    for i in "${!ITEM_IDS[@]}"; do
        if [ "${ITEM_IDS[$i]}" = "$id" ]; then
            SELECTED[$i]="$value"
            return 0
        fi
    done
    return 1
}

selected() {
    local id="$1" i
    for i in "${!ITEM_IDS[@]}"; do
        if [ "${ITEM_IDS[$i]}" = "$id" ]; then
            [ "${SELECTED[$i]}" -eq 1 ]
            return
        fi
    done
    return 1
}

selector_restore() {
    stty sane 2>/dev/null || true
    printf '\033[?25h'
}

draw_selector() {
    local i marker
    printf '\033[2J\033[H'
    
    printf "%b%bbootstrap-new-mac%b\n\n" "$BOLD" "$CYAN" "$RESET"
    if [ "$TEST_MODE" = true ]; then
        printf "%b%bTEST MODE — NO CHANGES WILL BE MADE%b\n\n" "$BOLD" "$YELLOW" "$RESET"
    fi
    
    printf "Select what to install/configure\n\n"
    printf "%b↑/↓ Move    Space Select    A Select all    N Select none%b\n" "$YELLOW" "$RESET"
    printf "%bEnter Continue    Q Quit%b\n\n" "$YELLOW" "$RESET"
    printf "%b────────────────────────────────────────────────────────────────────%b\n" "$YELLOW" "$RESET"

    for i in "${!ITEM_IDS[@]}"; do
        if [ "${SELECTED[$i]}" -eq 1 ]; then marker="●"; else marker="○"; fi
        if [ "$i" -eq "$SELECTOR_INDEX" ]; then
            printf "%b> %s %s%b\n" "$BOLD" "$marker" "${ITEM_LABELS[$i]}" "$RESET"
        else
            printf "  %s %s\n" "$marker" "${ITEM_LABELS[$i]}"
        fi
    done

    printf "%b────────────────────────────────────────────────────────────────────%b\n" "$YELLOW" "$RESET"
}

interactive_selector() {
    local key seq i
    SELECTOR_INDEX=0

    if [ ! -t 0 ] || [ ! -t 1 ]; then
        error "Interactive selector requires a terminal."
        exit 1
    fi

    # Put stdin into character-at-a-time mode.
    #
    # IMPORTANT:
    # Do not use dd/od/tr here. Those external-process pipelines can
    # interfere with escape-sequence input in Ghostty/macOS terminals.
    stty -echo -icanon 2>/dev/null || {
        error "Could not configure terminal for interactive selector."
        exit 1
    }

    printf '\033[?25l'
    trap 'selector_restore; exit 130' INT TERM HUP

    while true; do
        draw_selector

        # Read exactly one input character using Bash's builtin read.
        # This keeps arrow-key handling inside the same process.
        IFS= read -rsn1 key

        case "$key" in
            $'\e')
                # Arrow keys are ESC [ A/B.
                IFS= read -rsn2 seq
                case "$seq" in
                    '[A')
                        [ "$SELECTOR_INDEX" -gt 0 ] &&
                            SELECTOR_INDEX=$((SELECTOR_INDEX - 1))
                        ;;
                    '[B')
                        if [ "$SELECTOR_INDEX" -lt $((${#ITEM_IDS[@]} - 1)) ]; then
                            SELECTOR_INDEX=$((SELECTOR_INDEX + 1))
                        fi
                        ;;
                esac
                ;;
            ' ')
                if [ "${SELECTED[$SELECTOR_INDEX]}" -eq 1 ]; then
                    SELECTED[$SELECTOR_INDEX]=0
                else
                    SELECTED[$SELECTOR_INDEX]=1
                fi
                ;;
            a|A)
                for i in "${!SELECTED[@]}"; do SELECTED[$i]=1; done
                ;;
            n|N)
                for i in "${!SELECTED[@]}"; do SELECTED[$i]=0; done
                ;;
            '')
                # Enter produces an empty key with Bash read -n 1.
                selector_restore
                printf '\033[2J\033[H'
                trap - INT TERM HUP
                return 0
                ;;
            $'\r')
                # Keep CR handling as a fallback for terminals that return it.
                selector_restore
                printf '\033[2J\033[H'
                trap - INT TERM HUP
                return 0
                ;;
            q|Q)
                selector_restore
                printf '\n'
                exit 0
                ;;
        esac
    done
}

validate_selection_dependencies() {
    local id

    for id in \
        coreutils htop btop starship ghostty \
        jetbrains_mono_nerd_font caskaydia_mono_nerd_font \
        nvm node20 node22 java17 python3 stats itsycal vlc \
        brave_browser duckduckgo firefox telegram sublime_text \
        transmission outline_manager localsend intellij_idea_ce raycast; do
        if selected "$id" && ! selected homebrew; then
            set_selected homebrew 1
            warn "Homebrew required by selected items; Homebrew selected as a dependency."
            break
        fi
    done

    if (selected node20 || selected node22 || selected node_default22) && ! selected nvm; then
        set_selected nvm 1
        warn "NVM required by selected Node.js items; NVM selected as a dependency."
    fi

    if selected node_default22 && ! selected node22; then
        set_selected node22 1
        warn "Node.js 22 required for default version 22; Node.js 22 selected as a dependency."
    fi

    if selected login_stats && ! selected stats; then
        set_selected stats 1
        warn "Stats required by its login item; Stats selected as a dependency."
    fi

    if selected login_itsycal && ! selected itsycal; then
        set_selected itsycal 1
        warn "Itsycal required by its login item; Itsycal selected as a dependency."
    fi

    if selected login_raycast && ! selected raycast; then
        set_selected raycast 1
        warn "Raycast required by its login item; Raycast selected as a dependency."
    fi
}

print_selection_summary() {
    local i count=0
    section "SELECTED PLAN"
    for i in "${!ITEM_IDS[@]}"; do
        if [ "${SELECTED[$i]}" -eq 1 ]; then
            printf "  %b●%b %s\n" "$GREEN" "$RESET" "${ITEM_LABELS[$i]}"
            count=$((count + 1))
        fi
    done
    printf "\nSelected: %d of %d\n" "$count" "${#ITEM_IDS[@]}"
}

heartbeat() {
    while [ "$HB_RUNNING" = true ]; do
        sleep "$HEARTBEAT_INTERVAL"
        [ "$HB_RUNNING" = true ] || break
        printf "%b[ELAPSED] %s%b\n" "$PINK" "$(format_duration "$(( $(date +%s) - SCRIPT_START ))")" "$RESET"
    done
}

cleanup() {
    HB_RUNNING=false
    if [ -n "${HB_PID:-}" ] && kill -0 "$HB_PID" 2>/dev/null; then
        kill "$HB_PID" 2>/dev/null || true
        wait "$HB_PID" 2>/dev/null || true
    fi
    selector_restore 2>/dev/null || true
}
trap cleanup EXIT

if [[ "${OSTYPE-}" != darwin* ]]; then
    error "This bootstrap is intended for macOS."
    exit 1
fi

if [ "$AUTO" = true ]; then
    info "Auto mode: all items selected."
else
    interactive_selector
fi

validate_selection_dependencies
print_selection_summary

if [ "$TEST_MODE" = true ]; then
    section "TEST MODE — NO CHANGES WILL BE MADE"
    printf "The selected plan would perform:\n\n"
    for i in "${!ITEM_IDS[@]}"; do
        if [ "${SELECTED[$i]}" -eq 1 ]; then
            printf "  %b[TEST]%b %s\n" "$CYAN" "$RESET" "${ITEM_LABELS[$i]}"
        fi
    done
    printf "\n%bTEST MODE COMPLETE — no changes were made.%b\n" "$GREEN" "$RESET"
    exit 0
fi

if [ "$AUTO" = false ]; then
    printf "\n%bPress Enter to begin...%b" "$YELLOW" "$RESET"
    IFS= read -r
fi

heartbeat &
HB_PID=$!

if selected homebrew; then
    section "Homebrew"
    if command -v brew >/dev/null 2>&1; then
        skip "Homebrew — already installed."
        record SKIPPED "Homebrew"
    else
        run_task "Installing Homebrew" /bin/bash -c \
            "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        if [ -x /opt/homebrew/bin/brew ]; then
            eval "$(/opt/homebrew/bin/brew shellenv)" 2>/dev/null || true
        elif [ -x /usr/local/bin/brew ]; then
            eval "$(/usr/local/bin/brew shellenv)" 2>/dev/null || true
        fi
    fi
    if command -v brew >/dev/null 2>&1; then
        run_task "Updating Homebrew metadata (no package upgrades)" brew update
    else
        error "Homebrew is unavailable; dependent items will report errors and continue."
        record FAILED "Homebrew unavailable"
    fi
fi

if selected coreutils; then
    section "coreutils"
    if command -v brew >/dev/null 2>&1; then install_formula coreutils coreutils
    else error "coreutils — skipped because Homebrew is unavailable."; record FAILED "coreutils: Homebrew unavailable"; fi
fi

if selected htop; then
    section "htop"
    if command -v brew >/dev/null 2>&1; then install_formula htop htop
    else error "htop — skipped because Homebrew is unavailable."; record FAILED "htop: Homebrew unavailable"; fi
fi

if selected btop; then
    section "btop"
    if command -v brew >/dev/null 2>&1; then install_formula btop btop
    else error "btop — skipped because Homebrew is unavailable."; record FAILED "btop: Homebrew unavailable"; fi
fi

if selected starship; then
    section "Starship"
    if command -v brew >/dev/null 2>&1; then install_formula starship Starship
    else error "Starship — skipped because Homebrew is unavailable."; record FAILED "Starship: Homebrew unavailable"; fi
fi

install_selected_cask() {
    local id="$1" cask="$2" label="$3"
    selected "$id" || return 0
    section "$label"
    if command -v brew >/dev/null 2>&1; then
        install_cask "$cask" "$label"
    else
        error "$label — skipped because Homebrew is unavailable."
        record FAILED "$label: Homebrew unavailable"
    fi
}

install_selected_cask ghostty ghostty Ghostty
install_selected_cask jetbrains_mono_nerd_font font-jetbrains-mono-nerd-font "JetBrains Mono Nerd Font"
install_selected_cask caskaydia_mono_nerd_font font-caskaydia-mono-nerd-font "CaskaydiaMono Nerd Font"
install_selected_cask stats stats Stats
install_selected_cask itsycal itsycal Itsycal
install_selected_cask vlc vlc VLC
install_selected_cask brave_browser brave-browser "Brave Browser"
install_selected_cask duckduckgo duckduckgo DuckDuckGo
install_selected_cask firefox firefox Firefox
install_selected_cask telegram telegram Telegram
install_selected_cask sublime_text sublime-text "Sublime Text"
install_selected_cask transmission transmission Transmission
install_selected_cask outline_manager outline-manager "Outline Manager"
install_selected_cask localsend localsend LocalSend
install_selected_cask intellij_idea_ce intellij-idea-ce "IntelliJ IDEA Community Edition"
install_selected_cask raycast raycast Raycast

if selected java17; then
    section "Java 17 (Azul Zulu JDK 17)"

    # Detect Java 17 by the actual JDK installation, not only by Homebrew.
    # This prevents reinstalling an existing Azul Zulu 17 JDK that was
    # installed outside Homebrew.
    JAVA17_HOME="$(/usr/libexec/java_home -v 17 2>/dev/null || true)"
    JAVA17_VENDOR=""
    if [ -n "$JAVA17_HOME" ] && [ -x "$JAVA17_HOME/bin/java" ]; then
        JAVA17_VENDOR="$($JAVA17_HOME/bin/java -XshowSettings:properties -version 2>&1 | awk -F'= ' '/java.vendor =/{print $2; exit}')"
    fi

    if [ -n "$JAVA17_HOME" ]; then
        if printf '%s' "$JAVA17_VENDOR" | grep -Eiq 'Azul|Zulu'; then
            skip "Java 17 (Azul Zulu JDK 17) — already installed."
            record SKIPPED "Java 17 (Azul Zulu JDK 17)"
        else
            warn "Java 17 is already installed, but its vendor is: ${JAVA17_VENDOR:-unknown}."
            warn "Not replacing an existing Java 17 installation automatically."
            record SKIPPED "Java 17 — existing non-Zulu JDK"
        fi
    elif command -v brew >/dev/null 2>&1; then
        install_cask zulu@17 "Java 17 (Azul Zulu JDK 17)"
    else
        error "Java 17 — Homebrew is unavailable and no Java 17 installation was found."
        record FAILED "Java 17: unavailable"
    fi
fi

if selected python3; then
    section "Python 3"

    # Treat any usable Python 3 as already installed. The script does not
    # replace Apple's system Python or an existing user-managed Python.
    if command -v python3 >/dev/null 2>&1; then
        PYTHON3_VERSION="$(python3 --version 2>&1 || true)"
        skip "Python 3 — already installed (${PYTHON3_VERSION})."
        record SKIPPED "Python 3"
    elif command -v brew >/dev/null 2>&1; then
        install_cask python "Python 3"
    else
        error "Python 3 — Homebrew is unavailable and no Python 3 was found."
        record FAILED "Python 3: unavailable"
    fi
fi

if selected nvm; then
    section "NVM"
    NVM_DIR="$HOME/.nvm"
    NVM_VERSION="v0.40.3"
    if [ -s "$NVM_DIR/nvm.sh" ]; then
        skip "NVM — already installed."
        record SKIPPED "NVM"
    else
        run_task "Installing NVM $NVM_VERSION" bash -c \
            "export PROFILE=/dev/null NVM_DIR=\"$NVM_DIR\"; curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash"
    fi
fi

if selected node20; then
    section "Node.js 20"
    if [ -s "$HOME/.nvm/nvm.sh" ]; then
        if bash -c 'export NVM_DIR="$HOME/.nvm"; . "$NVM_DIR/nvm.sh"; nvm ls 20 >/dev/null 2>&1'; then
            skip "Node.js 20 — already installed."
            record SKIPPED "Node.js 20"
        else
            run_task "Installing Node.js 20" bash -c \
                'export NVM_DIR="$HOME/.nvm"; . "$NVM_DIR/nvm.sh"; nvm install 20'
        fi
    else
        error "Node.js 20 — NVM is unavailable."
        record FAILED "Node.js 20: NVM unavailable"
    fi
fi

if selected node22; then
    section "Node.js 22"
    if [ -s "$HOME/.nvm/nvm.sh" ]; then
        if bash -c 'export NVM_DIR="$HOME/.nvm"; . "$NVM_DIR/nvm.sh"; nvm ls 22 >/dev/null 2>&1'; then
            skip "Node.js 22 — already installed."
            record SKIPPED "Node.js 22"
        else
            run_task "Installing Node.js 22" bash -c \
                'export NVM_DIR="$HOME/.nvm"; . "$NVM_DIR/nvm.sh"; nvm install 22'
        fi
    else
        error "Node.js 22 — NVM is unavailable."
        record FAILED "Node.js 22: NVM unavailable"
    fi
fi

if selected node_default22; then
    section "Node.js default version: 22"
    if [ -s "$HOME/.nvm/nvm.sh" ]; then
        run_task "Setting NVM default to Node.js 22" bash -c \
            'export NVM_DIR="$HOME/.nvm"; . "$NVM_DIR/nvm.sh"; nvm alias default 22'
    else
        error "Could not set Node.js default — NVM is unavailable."
        record FAILED "Node.js default 22: NVM unavailable"
    fi
fi

if selected bash_profile; then
    section "~/.bash_profile"
    copy_config "$CONFIG_DIR/bash_profile" "$HOME/.bash_profile" "~/.bash_profile"
fi

if selected bashrc; then
    section "~/.bashrc"
    copy_config "$CONFIG_DIR/bashrc" "$HOME/.bashrc" "~/.bashrc"
fi

if selected shell_tools; then
    section "~/.shell-tools"
    copy_config "$CONFIG_DIR/shell-tools" "$HOME/.shell-tools" "~/.shell-tools"
fi

if selected starship_config; then
    section "~/.config/starship.toml"
    copy_config "$CONFIG_DIR/starship.toml" "$HOME/.config/starship.toml" "~/.config/starship.toml"
fi

if selected ghostty_config; then
    section "Ghostty configuration"
    copy_config \
        "$CONFIG_DIR/ghostty-config" \
        "$HOME/Library/Application Support/com.mitchellh.ghostty/config" \
        "Ghostty configuration"
fi

if selected shell_tools && [ -f "$HOME/.shell-tools" ]; then
    chmod +x "$HOME/.shell-tools" 2>/dev/null || {
        warn "Could not mark ~/.shell-tools executable."
        record WARNINGS "~/.shell-tools chmod failed"
    }
fi

add_login_item() {
    local id="$1" app_name="$2" app_path="$3"
    selected "$id" || return 0

    section "macOS Login Item: $app_name"

    if [ ! -d "$app_path" ]; then
        error "$app_name — application not found at $app_path"
        record FAILED "Login item: $app_name application missing"
        return 0
    fi

    local existing
    existing=$(osascript \
        -e 'tell application "System Events" to get the name of every login item' \
        2>/dev/null || true)

    if printf '%s\n' "$existing" | grep -Fqx "$app_name"; then
        skip "$app_name — already a login item."
        record SKIPPED "Login item: $app_name"
        return 0
    fi

    run_task "Adding $app_name to macOS Login Items" \
        osascript \
        -e "tell application \"System Events\" to make login item at end with properties {path:\"$app_path\", hidden:false}"
}

add_login_item login_stats Stats "/Applications/Stats.app"
add_login_item login_itsycal Itsycal "/Applications/Itsycal.app"
add_login_item login_raycast Raycast "/Applications/Raycast.app"

section "VALIDATION"

validate_command() {
    local label="$1"
    shift
    if "$@" >/dev/null 2>&1; then
        ok "$label"
    else
        error "$label"
        record FAILED "Validation: $label"
    fi
}

if selected homebrew; then validate_command "Homebrew" command -v brew; fi
if selected coreutils; then validate_command "coreutils / gls" command -v gls; fi
if selected htop; then validate_command "htop" command -v htop; fi
if selected btop; then validate_command "btop" command -v btop; fi
if selected starship; then validate_command "Starship" command -v starship; fi
if selected ghostty; then validate_command "Ghostty application" test -d "/Applications/Ghostty.app"; fi
if selected jetbrains_mono_nerd_font; then validate_command "JetBrains Mono Nerd Font" brew list --cask font-jetbrains-mono-nerd-font; fi
if selected caskaydia_mono_nerd_font; then validate_command "CaskaydiaMono Nerd Font" brew list --cask font-caskaydia-mono-nerd-font; fi
if selected nvm; then validate_command "NVM" test -s "$HOME/.nvm/nvm.sh"; fi
if selected node20; then validate_command "Node.js 20" bash -c 'export NVM_DIR="$HOME/.nvm"; . "$NVM_DIR/nvm.sh"; nvm ls 20 >/dev/null 2>&1'; fi
if selected node22; then validate_command "Node.js 22" bash -c 'export NVM_DIR="$HOME/.nvm"; . "$NVM_DIR/nvm.sh"; nvm ls 22 >/dev/null 2>&1'; fi
if selected java17; then
    validate_command "Java 17" bash -c '/usr/libexec/java_home -v 17 >/dev/null 2>&1'
fi
if selected python3; then
    validate_command "Python 3" python3 --version
fi

for pair in \
    "stats|Stats|/Applications/Stats.app" \
    "itsycal|Itsycal|/Applications/Itsycal.app" \
    "vlc|VLC|/Applications/VLC.app" \
    "brave_browser|Brave Browser|/Applications/Brave Browser.app" \
    "duckduckgo|DuckDuckGo|/Applications/DuckDuckGo.app" \
    "firefox|Firefox|/Applications/Firefox.app" \
    "telegram|Telegram|/Applications/Telegram.app" \
    "sublime_text|Sublime Text|/Applications/Sublime Text.app" \
    "transmission|Transmission|/Applications/Transmission.app" \
    "outline_manager|Outline Manager|/Applications/Outline Manager.app" \
    "localsend|LocalSend|/Applications/LocalSend.app" \
    "intellij_idea_ce|IntelliJ IDEA Community Edition|/Applications/IntelliJ IDEA CE.app" \
    "raycast|Raycast|/Applications/Raycast.app"; do

    IFS='|' read -r id label app_path <<< "$pair"
    if selected "$id"; then
        validate_command "$label application" test -d "$app_path"
    fi
done

if selected bash_profile; then validate_command "~/.bash_profile" test -f "$HOME/.bash_profile"; fi
if selected bashrc; then validate_command "~/.bashrc" test -f "$HOME/.bashrc"; fi
if selected shell_tools; then validate_command "~/.shell-tools" test -f "$HOME/.shell-tools"; fi
if selected starship_config; then validate_command "~/.config/starship.toml" test -f "$HOME/.config/starship.toml"; fi
if selected ghostty_config; then
    validate_command "Ghostty configuration" \
        test -f "$HOME/Library/Application Support/com.mitchellh.ghostty/config"
fi

TOTAL_ELAPSED=$(( $(date +%s) - SCRIPT_START ))

section "FINAL SUMMARY — $(format_duration "$TOTAL_ELAPSED")"

print_array() {
    local title="$1" color="$2"
    shift 2
    local -a values=("$@")

    printf "%b%s%b\n" "$color" "$title" "$RESET"

    if [ "${#values[@]}" -eq 0 ]; then
        printf "  - none\n\n"
        return
    fi

    local value
    for value in "${values[@]}"; do
        printf "  %b- %s%b\n" "$color" "$value" "$RESET"
    done
    printf "\n"
}

#print_array "Installed:" "$GREEN" "${INSTALLED[@]}"
#print_array "Skipped — already exists:" "$YELLOW" "${SKIPPED[@]}"
#print_array "Configured:" "$GREEN" "${CONFIGURED[@]}"
#print_array "Warnings:" "$ORANGE" "${WARNINGS[@]}"
#print_array "Errors:" "$RED" "${FAILED[@]}"
print_array "Installed:" "$GREEN" "${INSTALLED[@]:0}"
print_array "Skipped — already exists:" "$YELLOW" "${SKIPPED[@]:0}"
print_array "Configured:" "$GREEN" "${CONFIGURED[@]:0}"
print_array "Warnings:" "$ORANGE" "${WARNINGS[@]:0}"
print_array "Errors:" "$RED" "${FAILED[@]:0}"


if [ "${#FAILED[@]}" -eq 0 ]; then
    ok "Bootstrap completed successfully."
    exit 0
fi

error "Bootstrap completed with ${#FAILED[@]} error(s)."
printf "The installer continued through the remaining selected tasks.\n"
exit 1
